image: docker:latest
services:
  - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

stages:
  - build
  - test

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

lint:
  stage: test
  script:
    - docker run --rm $IMAGE_TAG find {{ project_name }}/ -name "*.py" ! -path "{{ project_name }}/settings/*" ! -path "{{ project_name }}/urls.py" ! -path "{{ project_name }}/wsgi.py" -exec pylint -ry {} +

unittest:
  stage: test
  script:
    - docker run -d -e DATABASE_HOST=postgres -e DATABASE_USER=postgres -e DATABASE_PASSWORD="mypassword" --name service-postgres postgres:9.6
    - docker run --rm --link=service-postgres:postgres $IMAGE_TAG sh -c 'coverage run manage.py test {{ project_name }}.tests && coverage html && coverage report'
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+)/'
