version: '3'
services:
  postgres:
    image: postgres:9.6
    container_name: {{ project_name }}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB={{ project_name }}
